### ISSUE TITLE
checklist for lecturer stage 2

### ISSUE THREAD

**Issue by lkrol8006** [Gharte15/MP08_KM_LK_WSPOLBIEZNE#6]
**1. Starting point**

- [x] all UT are green
- [x] the program behaves as expected (intermediate approval test)

**2. Data Layer**

- [ ] responsibility of this layer is to represent boundaries of the movement rectangle and balls
- [ ] balls representation are independent and self-contained (no timer required)
- [ ] balls implementation uses parallel programming if applicable (depends on the run time platform)

**3. Logic Layer**

- [ ] responsibility of this layer is to manage movement rectangle boundaries and balls interaction (collisions)
- [ ] prove that the protection of data integration is implemented
- [ ] Logic uses only the abstract Data layer API

**4. Presentation Layer (mvvm)**

- [ ] responsibility of this layer is to manage the graphical user interface (GUI)
- [ ] user => GUI interoperability must be implemented using interactive programming only
- [ ] GUI => the user interoperability must be implemented using reactive programming only (timer is not allowed)
- [ ] interoperability of the GUI and underlying layers must be synchronized

**5. Testing**

- [ ] Unit Test - layers are tested independently using dependency injection (additional framework is not required)
- [ ] Mock may be used for testing purpose (expected but not required)
